CREATE TABLE `#__podcast_feeds` (
	`feed_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`feed_default` tinyint(1) DEFAULT '0',
	`feed_title` varchar(255) DEFAULT NULL,
	`feed_alias` varchar(255) DEFAULT NULL,
	`feed_link` varchar(255) DEFAULT NULL,
	`feed_language` varchar(255) DEFAULT NULL,
	`feed_copyright` varchar(255) DEFAULT NULL,
	`feed_subtitle` varchar(255) DEFAULT NULL,
	`feed_author` varchar(255) DEFAULT NULL,
	`feed_block` tinyint(1) DEFAULT '0',
	`feed_explicit` tinyint(1) DEFAULT '0',
	`feed_keywords` varchar(255) DEFAULT NULL,
	`feed_summary` text,
	`feed_description` text,
	`feed_owner_name` varchar(255) DEFAULT NULL,
	`feed_owner_email` varchar(255) DEFAULT NULL,
	`feed_image` varchar(511) DEFAULT NULL,
	`feed_category1` varchar(255) DEFAULT NULL,
	`feed_category2` varchar(255) DEFAULT NULL,
	`feed_category3` varchar(255) DEFAULT NULL,
	`feed_new_feed_url` varchar(511) DEFAULT NULL,
	`feed_complete` tinyint(1) DEFAULT '0',
	`feed_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`published` tinyint(1) DEFAULT '0',
	PRIMARY KEY (`feed_id`),
	KEY `feed_alias` (`feed_alias`)
);

CREATE TABLE `#__podcast_media` (
	`media_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`feed_id` int(11) DEFAULT NULL,
	`item_title` varchar(255) DEFAULT NULL,
	`item_alias` varchar(255) DEFAULT NULL,
	`item_author` varchar(255) DEFAULT NULL,
	`item_subtitle` varchar(255) DEFAULT NULL,
	`item_summary` text,
	`item_description` text,
	`item_enclosure_url` varchar(511) DEFAULT NULL,
	`item_enclosure_length` varchar(31) DEFAULT NULL,
	`item_enclosure_type` varchar(255) DEFAULT NULL,
	`item_guid` varchar(255) DEFAULT NULL,
	`item_pubDate` datetime DEFAULT NULL,
	`item_duration` varchar(31) DEFAULT NULL,
	`item_keywords` varchar(255) DEFAULT NULL,
	`item_isClosedCaptioned` tinyint(1) DEFAULT '0',
	`item_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`published` tinyint(1) DEFAULT '0',
	PRIMARY KEY (`media_id`),
	KEY `feed_id` (`feed_id`),
	KEY `item_alias` (`item_alias`)
);